name: th-test-utils
version: 1.1.1
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE
author:
  - Brandon Chinn <brandon@leapyear.io>
maintainer:
  - Brandon Chinn <brandon@leapyear.io>
category: Testing
synopsis: Utility functions for testing Template Haskell code
description: |
  Utility functions for testing Template Haskell code, including
  functions for testing failures in the Q monad.
extra-source-files:
  - README.md
  - CHANGELOG.md

github: LeapYear/th-test-utils

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

dependencies:
- base >= 4.9 && < 5
- template-haskell >= 2.11.1.0 && <2.19
- th-orphans >= 0.13.4 && <0.14
- transformers >= 0.5.2 && < 0.6

library:
  source-dirs: src

tests:
  th-test-utils-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - bytestring
      - tasty
      - tasty-golden
      - tasty-hunit
      - th-test-utils
